export enum IconName {
  CAMERA = 'camera',
  CHEVRON = 'chevron',
  CLOCK = 'clock',
  CROSS = 'cross',
  DONE = 'done',
  ERROR = 'error',
  EYESLASH = 'eyeslash',
  EYE = 'eye',
  FILE = 'file',
  FILTER = 'filter',
  FILTERS = 'filters',
  HOME = 'home',
  LEAF = 'leaf',
  LOCK = 'lock',
  MAPS = 'maps',
  PHONE = 'phone',
  SEARCH = 'search',
  STORY = 'story',
  TH = 'th',
  USER = 'user',
}
