export enum IconName {
  CHEVRON = 'chevron',
  CLOCK = 'clock',
  CROSS = 'cross',
  DONE = 'done',
  FILE = 'file',
  FILTER = 'filter',
  HOME = 'home',
  LEAF = 'leaf',
  LOCK = 'lock',
  MAPS = 'maps',
  PHONE = 'phone',
  SEARCH = 'search',
  STORY = 'story',
  TH = 'th',
  USER = 'user',
}
